Apply MVP Structure
awesome-academy/HN_Naitei57_Android_Wheather_App pull request #2
Opened 2024-08-02 08:09 UTC by dungd200803btvn

## Related Tickets
- [#Task78699: Content](https://edu-redmine.sun-asterisk.vn/issues/78699)
## WHAT
Initial project with MVP structure
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-08-06 07:49 UTC, gianghv-3456 requested changes
Check my cmts

2024-08-06 07:49 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/CurrentWeatherRemoteDataSource.kt
> +    override fun getCurrentWeather(listener: OnResultListener<MutableList<CurrentWeather>>) {
Sử dụng List thay vì Mutable List vì data trả về từ Data Source CỐ ĐỊNH. Việc xử lý tiếp theo cần tới mutable thì nó ở Repository
```suggestion
    override fun getCurrentWeather(listener: OnResultListener<List<CurrentWeather>>) {
```

2024-08-06 07:49 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/GetJsonFromUrl.kt
> +    private val mExecutor: Executor = Executors.newSingleThreadExecutor()
Sử dụng các dạng Executor khác để đảm bảo hiệu suất đa luồng
```suggestion
    
```

2024-08-06 07:49 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/GetJsonFromUrl.kt
> +    private val mExecutor: Executor = Executors.newSingleThreadExecutor()
Có thể tìm hiểu - sử dụng Callable hoặc Future

2024-08-06 07:49 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/GetJsonFromUrl.kt
> +    }
Kiểm soát lỗi của phần này là vô cùng quan trọng. Anh chưa thấy em xử lý các Exception về mạng và về IO

2024-08-06 07:49 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/ParseDataWithJson.kt
> +    }
Dùng GSON đi em

2024-08-06 07:49 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/local/CurrentWeatherLocalDataSource.kt
> +    override fun getCurrentWeatherLocal(listener: OnResultListener<MutableList<CurrentWeather>>) {
Use List instead of MutableList
```suggestion
    override fun getCurrentWeatherLocal(listener: OnResultListener<List<CurrentWeather>>) {
```

2024-08-06 07:49 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/utils/Constant.kt
> +    const val BASE_API_KEY = "b90eddc6e7dc210d88ab411424ef64b8"
Không đặt API Key trong Source Code em nhé. Đặt trong source code có thể bị ăn cắp và để lại rất nhiều hậu quả

2024-08-06 07:49 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/utils/Constant.kt
> +    const val BASE_API_KEY = "b90eddc6e7dc210d88ab411424ef64b8"
Nghiên cứu tìm cách giấu API key trong gradle Build Config

2024-08-06 09:42 UTC, gianghv-3456 requested changes
Check my cmts

2024-08-06 09:42 UTC, gianghv-3456 commented on gradlew.bat
Sao lại có file này ở đây em, nó không được nằm trong Pull Request

2024-08-06 09:42 UTC, gianghv-3456 commented on gradlew
File này cũng vậy? Git Ignore của em sai à?

2024-08-06 09:42 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/utils/OnItemRecyclerViewClickListener.kt
Cái này đã cần dùng chưa vậy em, chưa thì đừng đẩy lên

2024-08-06 09:42 UTC, gianghv-3456 commented on app/build.gradle
Chạy detekt chưa em

2024-08-06 09:42 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/ParseDataWithJson.kt
> +        return data
Áp dụng GSON đi em, không làm thế này. JSONObject tiềm ẩn rất nhiều hạn chế

2024-08-06 09:42 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/GetJsonFromUrl.kt
> +) {
Em làm thế này thì SIngleTon chẳng có ý nghĩa gì vì mỗi một API em lại tạo ra một handler mới. Listener và clazz là những thứ nên nằm trong Parameter của hàm thay vì khởi tạo cả Object, Object này nên chứa hàm và Thread pool thôi

2024-08-06 09:42 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/GetJsonFromUrl.kt
> +) {
Nếu mà mỗi API là một object, và cái object đấy lại chứa ThreadPool thì sẽ tạo ra rất nhiều Thread đấy

2024-08-06 09:42 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/CurrentWeatherRemoteDataSource.kt
Hàm trống không làm việc gì cả thì Pull Request lên làm gì em???

2024-08-06 09:47 UTC, dungd200803btvn commented on app/build.gradle
rồi ạ

2024-08-06 09:53 UTC, dungd200803btvn commented on gradlew
mấy commit trước e ko bị, k hiểu sao sửa để thêm API key xong nó lại sinh ra 2 cái file này nên bị

2024-08-06 10:48 UTC, gianghv-3456 requested changes
check my cmt

2024-08-06 10:48 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/ApiManager.kt
> +    private val mExecutor: ExecutorService = Executors.newFixedThreadPool(1)
Sao lại để pool size = 1 vậy em? và cũng không hard code thế này nhé
```suggestion
    private val mExecutor: ExecutorService = Executors.newFixedThreadPool(1)
```

2024-08-06 10:48 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/ApiManager.kt
> +                Log.e("myTag", "HTTP error code: ${httpURLConnection?.responseCode}")
Tạo constant cho log tag đi em, và cũng không log e, log d nhé

2024-08-06 10:48 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/ApiManager.kt
> +    private const val METHOD_GET = "GET"
Không khai báo ở cuối file như vậy e. Tuân thủ đúng thứ tự sắp xếp theo convention nhé

2024-08-06 10:48 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/ remote/fetchjson/ParseDataWithJson.kt
> +            }
=))) em vẫn cần học lại cách dùng GSON. Đây là em copy từ ChatGPT chứ không phải là tìm hiểu rồi. Đọc cách dùng đi em, tham khảo [link này](https://viblo.asia/p/lam-viec-voi-gson-trong-android-7rVRqwNJG4bP)

2024-08-07 08:04 UTC, gianghv-3456 approved these changes
okay

2024-08-07 08:04 UTC, merged